### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by ww9980** [jcts3/whenismytrain#9]
I followed the instruction to run the server but got error message 'not found'. 

I found that in 'routeinfo.js' line 11,

rather than "const address = `https://${apiEP}json/search/${origin}/to/${destination}`;"

it should be "const address = `https://${apiEP}/json/search/${origin}/to/${destination}`;"

**Comment by jcts3** [comment]
I think you are correct! I may have had the `info.Endpoint` with a `/` on the end in my local config file but left off the `/` in `info_template.json`. Using your suggestion is more robust though, so I will change it 😄

**Comment by ww9980** [comment]
Cheers mate. Closing this topic as it's solved.
